baseURL = "https://XavTo.github.io/"
languageCode = "en-us"
title = "ArasBurger"
theme = "tailbliss"
paginate = 3
relativeURLs = true
canonifyURLs = false

[params]
  # Ajuste ces param√®tres en fonction de ton projet
  description = "Healthy, energizing meals with Arasgrasa."
  author = "Kement2"
  logo = "images/logo.png"

[build]
writeStats = true
[build.minify]
  minifyJs = true

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
